//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace BulgarianSights.DB
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SightsDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SightsDBEntities object using the connection string found in the 'SightsDBEntities' section of the application configuration file.
        /// </summary>
        public SightsDBEntities() : base("name=SightsDBEntities", "SightsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SightsDBEntities object.
        /// </summary>
        public SightsDBEntities(string connectionString) : base(connectionString, "SightsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SightsDBEntities object.
        /// </summary>
        public SightsDBEntities(EntityConnection connection) : base(connection, "SightsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CulturalAndHistoricSites> CulturalAndHistoricSites
        {
            get
            {
                if ((_CulturalAndHistoricSites == null))
                {
                    _CulturalAndHistoricSites = base.CreateObjectSet<CulturalAndHistoricSites>("CulturalAndHistoricSites");
                }
                return _CulturalAndHistoricSites;
            }
        }
        private ObjectSet<CulturalAndHistoricSites> _CulturalAndHistoricSites;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Documents> Documents
        {
            get
            {
                if ((_Documents == null))
                {
                    _Documents = base.CreateObjectSet<Documents>("Documents");
                }
                return _Documents;
            }
        }
        private ObjectSet<Documents> _Documents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EventSite> EventSite
        {
            get
            {
                if ((_EventSite == null))
                {
                    _EventSite = base.CreateObjectSet<EventSite>("EventSite");
                }
                return _EventSite;
            }
        }
        private ObjectSet<EventSite> _EventSite;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CulturalAndHistoricSites EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCulturalAndHistoricSites(CulturalAndHistoricSites culturalAndHistoricSites)
        {
            base.AddObject("CulturalAndHistoricSites", culturalAndHistoricSites);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Documents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDocuments(Documents documents)
        {
            base.AddObject("Documents", documents);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EventSite EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEventSite(EventSite eventSite)
        {
            base.AddObject("EventSite", eventSite);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SightsDBModel", Name="CulturalAndHistoricSites")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CulturalAndHistoricSites : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CulturalAndHistoricSites object.
        /// </summary>
        /// <param name="idSite">Initial value of the idSite property.</param>
        /// <param name="site">Initial value of the site property.</param>
        /// <param name="siteX">Initial value of the siteX property.</param>
        /// <param name="siteY">Initial value of the siteY property.</param>
        public static CulturalAndHistoricSites CreateCulturalAndHistoricSites(global::System.Int32 idSite, global::System.String site, global::System.String siteX, global::System.String siteY)
        {
            CulturalAndHistoricSites culturalAndHistoricSites = new CulturalAndHistoricSites();
            culturalAndHistoricSites.idSite = idSite;
            culturalAndHistoricSites.site = site;
            culturalAndHistoricSites.siteX = siteX;
            culturalAndHistoricSites.siteY = siteY;
            return culturalAndHistoricSites;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idSite
        {
            get
            {
                return _idSite;
            }
            set
            {
                if (_idSite != value)
                {
                    OnidSiteChanging(value);
                    ReportPropertyChanging("idSite");
                    _idSite = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idSite");
                    OnidSiteChanged();
                }
            }
        }
        private global::System.Int32 _idSite;
        partial void OnidSiteChanging(global::System.Int32 value);
        partial void OnidSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String site
        {
            get
            {
                return _site;
            }
            set
            {
                OnsiteChanging(value);
                ReportPropertyChanging("site");
                _site = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("site");
                OnsiteChanged();
            }
        }
        private global::System.String _site;
        partial void OnsiteChanging(global::System.String value);
        partial void OnsiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String siteName
        {
            get
            {
                return _siteName;
            }
            set
            {
                OnsiteNameChanging(value);
                ReportPropertyChanging("siteName");
                _siteName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("siteName");
                OnsiteNameChanged();
            }
        }
        private global::System.String _siteName;
        partial void OnsiteNameChanging(global::System.String value);
        partial void OnsiteNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String area
        {
            get
            {
                return _area;
            }
            set
            {
                OnareaChanging(value);
                ReportPropertyChanging("area");
                _area = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("area");
                OnareaChanged();
            }
        }
        private global::System.String _area;
        partial void OnareaChanging(global::System.String value);
        partial void OnareaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String age
        {
            get
            {
                return _age;
            }
            set
            {
                OnageChanging(value);
                ReportPropertyChanging("age");
                _age = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("age");
                OnageChanged();
            }
        }
        private global::System.String _age;
        partial void OnageChanging(global::System.String value);
        partial void OnageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String importance
        {
            get
            {
                return _importance;
            }
            set
            {
                OnimportanceChanging(value);
                ReportPropertyChanging("importance");
                _importance = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("importance");
                OnimportanceChanged();
            }
        }
        private global::System.String _importance;
        partial void OnimportanceChanging(global::System.String value);
        partial void OnimportanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String culture
        {
            get
            {
                return _culture;
            }
            set
            {
                OncultureChanging(value);
                ReportPropertyChanging("culture");
                _culture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("culture");
                OncultureChanged();
            }
        }
        private global::System.String _culture;
        partial void OncultureChanging(global::System.String value);
        partial void OncultureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String siteX
        {
            get
            {
                return _siteX;
            }
            set
            {
                OnsiteXChanging(value);
                ReportPropertyChanging("siteX");
                _siteX = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("siteX");
                OnsiteXChanged();
            }
        }
        private global::System.String _siteX;
        partial void OnsiteXChanging(global::System.String value);
        partial void OnsiteXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String siteY
        {
            get
            {
                return _siteY;
            }
            set
            {
                OnsiteYChanging(value);
                ReportPropertyChanging("siteY");
                _siteY = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("siteY");
                OnsiteYChanged();
            }
        }
        private global::System.String _siteY;
        partial void OnsiteYChanging(global::System.String value);
        partial void OnsiteYChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SightsDBModel", Name="Documents")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Documents : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Documents object.
        /// </summary>
        /// <param name="idDocument">Initial value of the idDocument property.</param>
        /// <param name="documentText">Initial value of the documentText property.</param>
        /// <param name="documentName">Initial value of the documentName property.</param>
        public static Documents CreateDocuments(global::System.Int32 idDocument, global::System.String documentText, global::System.String documentName)
        {
            Documents documents = new Documents();
            documents.idDocument = idDocument;
            documents.documentText = documentText;
            documents.documentName = documentName;
            return documents;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idDocument
        {
            get
            {
                return _idDocument;
            }
            set
            {
                if (_idDocument != value)
                {
                    OnidDocumentChanging(value);
                    ReportPropertyChanging("idDocument");
                    _idDocument = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idDocument");
                    OnidDocumentChanged();
                }
            }
        }
        private global::System.Int32 _idDocument;
        partial void OnidDocumentChanging(global::System.Int32 value);
        partial void OnidDocumentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String documentText
        {
            get
            {
                return _documentText;
            }
            set
            {
                OndocumentTextChanging(value);
                ReportPropertyChanging("documentText");
                _documentText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("documentText");
                OndocumentTextChanged();
            }
        }
        private global::System.String _documentText;
        partial void OndocumentTextChanging(global::System.String value);
        partial void OndocumentTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String documentName
        {
            get
            {
                return _documentName;
            }
            set
            {
                OndocumentNameChanging(value);
                ReportPropertyChanging("documentName");
                _documentName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("documentName");
                OndocumentNameChanged();
            }
        }
        private global::System.String _documentName;
        partial void OndocumentNameChanging(global::System.String value);
        partial void OndocumentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String area
        {
            get
            {
                return _area;
            }
            set
            {
                OnareaChanging(value);
                ReportPropertyChanging("area");
                _area = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("area");
                OnareaChanged();
            }
        }
        private global::System.String _area;
        partial void OnareaChanging(global::System.String value);
        partial void OnareaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String age
        {
            get
            {
                return _age;
            }
            set
            {
                OnageChanging(value);
                ReportPropertyChanging("age");
                _age = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("age");
                OnageChanged();
            }
        }
        private global::System.String _age;
        partial void OnageChanging(global::System.String value);
        partial void OnageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String importance
        {
            get
            {
                return _importance;
            }
            set
            {
                OnimportanceChanging(value);
                ReportPropertyChanging("importance");
                _importance = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("importance");
                OnimportanceChanged();
            }
        }
        private global::System.String _importance;
        partial void OnimportanceChanging(global::System.String value);
        partial void OnimportanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String culture
        {
            get
            {
                return _culture;
            }
            set
            {
                OncultureChanging(value);
                ReportPropertyChanging("culture");
                _culture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("culture");
                OncultureChanged();
            }
        }
        private global::System.String _culture;
        partial void OncultureChanging(global::System.String value);
        partial void OncultureChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SightsDBModel", Name="EventSite")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EventSite : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EventSite object.
        /// </summary>
        /// <param name="idEvent">Initial value of the idEvent property.</param>
        /// <param name="event">Initial value of the event property.</param>
        /// <param name="eventName">Initial value of the eventName property.</param>
        public static EventSite CreateEventSite(global::System.Int32 idEvent, global::System.String @event, global::System.String eventName)
        {
            EventSite eventSite = new EventSite();
            eventSite.idEvent = idEvent;
            eventSite.@event = @event;
            eventSite.eventName = eventName;
            return eventSite;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEvent
        {
            get
            {
                return _idEvent;
            }
            set
            {
                if (_idEvent != value)
                {
                    OnidEventChanging(value);
                    ReportPropertyChanging("idEvent");
                    _idEvent = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idEvent");
                    OnidEventChanged();
                }
            }
        }
        private global::System.Int32 _idEvent;
        partial void OnidEventChanging(global::System.Int32 value);
        partial void OnidEventChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String @event
        {
            get
            {
                return _event;
            }
            set
            {
                OneventChanging(value);
                ReportPropertyChanging("event");
                _event = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("event");
                OneventChanged();
            }
        }
        private global::System.String _event;
        partial void OneventChanging(global::System.String value);
        partial void OneventChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String eventName
        {
            get
            {
                return _eventName;
            }
            set
            {
                OneventNameChanging(value);
                ReportPropertyChanging("eventName");
                _eventName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("eventName");
                OneventNameChanged();
            }
        }
        private global::System.String _eventName;
        partial void OneventNameChanging(global::System.String value);
        partial void OneventNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String area
        {
            get
            {
                return _area;
            }
            set
            {
                OnareaChanging(value);
                ReportPropertyChanging("area");
                _area = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("area");
                OnareaChanged();
            }
        }
        private global::System.String _area;
        partial void OnareaChanging(global::System.String value);
        partial void OnareaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String age
        {
            get
            {
                return _age;
            }
            set
            {
                OnageChanging(value);
                ReportPropertyChanging("age");
                _age = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("age");
                OnageChanged();
            }
        }
        private global::System.String _age;
        partial void OnageChanging(global::System.String value);
        partial void OnageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.String _date;
        partial void OndateChanging(global::System.String value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CulturalAndHistoricSitesId
        {
            get
            {
                return _CulturalAndHistoricSitesId;
            }
            set
            {
                OnCulturalAndHistoricSitesIdChanging(value);
                ReportPropertyChanging("CulturalAndHistoricSitesId");
                _CulturalAndHistoricSitesId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CulturalAndHistoricSitesId");
                OnCulturalAndHistoricSitesIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CulturalAndHistoricSitesId;
        partial void OnCulturalAndHistoricSitesIdChanging(Nullable<global::System.Int32> value);
        partial void OnCulturalAndHistoricSitesIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SightsDBModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }

    #endregion
    
}
