//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SightsDBModel", "FK_Events_CulturalAndHistoricSites", "CulturalAndHistoricSites", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BulgarianSights.DB.CulturalAndHistoricSites), "Events", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BulgarianSights.DB.Events), true)]

#endregion

namespace BulgarianSights.DB
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SightsDBEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SightsDBEntities1 object using the connection string found in the 'SightsDBEntities1' section of the application configuration file.
        /// </summary>
        public SightsDBEntities1() : base("name=SightsDBEntities1", "SightsDBEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SightsDBEntities1 object.
        /// </summary>
        public SightsDBEntities1(string connectionString) : base(connectionString, "SightsDBEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SightsDBEntities1 object.
        /// </summary>
        public SightsDBEntities1(EntityConnection connection) : base(connection, "SightsDBEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CulturalAndHistoricSites> CulturalAndHistoricSites
        {
            get
            {
                if ((_CulturalAndHistoricSites == null))
                {
                    _CulturalAndHistoricSites = base.CreateObjectSet<CulturalAndHistoricSites>("CulturalAndHistoricSites");
                }
                return _CulturalAndHistoricSites;
            }
        }
        private ObjectSet<CulturalAndHistoricSites> _CulturalAndHistoricSites;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Documents> Documents
        {
            get
            {
                if ((_Documents == null))
                {
                    _Documents = base.CreateObjectSet<Documents>("Documents");
                }
                return _Documents;
            }
        }
        private ObjectSet<Documents> _Documents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Events> Events
        {
            get
            {
                if ((_Events == null))
                {
                    _Events = base.CreateObjectSet<Events>("Events");
                }
                return _Events;
            }
        }
        private ObjectSet<Events> _Events;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CulturalAndHistoricSites EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCulturalAndHistoricSites(CulturalAndHistoricSites culturalAndHistoricSites)
        {
            base.AddObject("CulturalAndHistoricSites", culturalAndHistoricSites);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Documents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDocuments(Documents documents)
        {
            base.AddObject("Documents", documents);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Events EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEvents(Events events)
        {
            base.AddObject("Events", events);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SightsDBModel", Name="CulturalAndHistoricSites")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CulturalAndHistoricSites : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CulturalAndHistoricSites object.
        /// </summary>
        /// <param name="idObject">Initial value of the idObject property.</param>
        /// <param name="object">Initial value of the object property.</param>
        /// <param name="objectX">Initial value of the objectX property.</param>
        /// <param name="objectY">Initial value of the objectY property.</param>
        public static CulturalAndHistoricSites CreateCulturalAndHistoricSites(global::System.Int32 idObject, global::System.String @object, global::System.Double objectX, global::System.Double objectY)
        {
            CulturalAndHistoricSites culturalAndHistoricSites = new CulturalAndHistoricSites();
            culturalAndHistoricSites.idObject = idObject;
            culturalAndHistoricSites.@object = @object;
            culturalAndHistoricSites.objectX = objectX;
            culturalAndHistoricSites.objectY = objectY;
            return culturalAndHistoricSites;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idObject
        {
            get
            {
                return _idObject;
            }
            set
            {
                if (_idObject != value)
                {
                    OnidObjectChanging(value);
                    ReportPropertyChanging("idObject");
                    _idObject = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idObject");
                    OnidObjectChanged();
                }
            }
        }
        private global::System.Int32 _idObject;
        partial void OnidObjectChanging(global::System.Int32 value);
        partial void OnidObjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String @object
        {
            get
            {
                return _object;
            }
            set
            {
                OnobjectChanging(value);
                ReportPropertyChanging("object");
                _object = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("object");
                OnobjectChanged();
            }
        }
        private global::System.String _object;
        partial void OnobjectChanging(global::System.String value);
        partial void OnobjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String objectName
        {
            get
            {
                return _objectName;
            }
            set
            {
                OnobjectNameChanging(value);
                ReportPropertyChanging("objectName");
                _objectName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("objectName");
                OnobjectNameChanged();
            }
        }
        private global::System.String _objectName;
        partial void OnobjectNameChanging(global::System.String value);
        partial void OnobjectNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String area
        {
            get
            {
                return _area;
            }
            set
            {
                OnareaChanging(value);
                ReportPropertyChanging("area");
                _area = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("area");
                OnareaChanged();
            }
        }
        private global::System.String _area;
        partial void OnareaChanging(global::System.String value);
        partial void OnareaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String age
        {
            get
            {
                return _age;
            }
            set
            {
                OnageChanging(value);
                ReportPropertyChanging("age");
                _age = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("age");
                OnageChanged();
            }
        }
        private global::System.String _age;
        partial void OnageChanging(global::System.String value);
        partial void OnageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String importance
        {
            get
            {
                return _importance;
            }
            set
            {
                OnimportanceChanging(value);
                ReportPropertyChanging("importance");
                _importance = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("importance");
                OnimportanceChanged();
            }
        }
        private global::System.String _importance;
        partial void OnimportanceChanging(global::System.String value);
        partial void OnimportanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String culture
        {
            get
            {
                return _culture;
            }
            set
            {
                OncultureChanging(value);
                ReportPropertyChanging("culture");
                _culture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("culture");
                OncultureChanged();
            }
        }
        private global::System.String _culture;
        partial void OncultureChanging(global::System.String value);
        partial void OncultureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eventId
        {
            get
            {
                return _eventId;
            }
            set
            {
                OneventIdChanging(value);
                ReportPropertyChanging("eventId");
                _eventId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eventId");
                OneventIdChanged();
            }
        }
        private Nullable<global::System.Int32> _eventId;
        partial void OneventIdChanging(Nullable<global::System.Int32> value);
        partial void OneventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double objectX
        {
            get
            {
                return _objectX;
            }
            set
            {
                OnobjectXChanging(value);
                ReportPropertyChanging("objectX");
                _objectX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("objectX");
                OnobjectXChanged();
            }
        }
        private global::System.Double _objectX;
        partial void OnobjectXChanging(global::System.Double value);
        partial void OnobjectXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double objectY
        {
            get
            {
                return _objectY;
            }
            set
            {
                OnobjectYChanging(value);
                ReportPropertyChanging("objectY");
                _objectY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("objectY");
                OnobjectYChanged();
            }
        }
        private global::System.Double _objectY;
        partial void OnobjectYChanging(global::System.Double value);
        partial void OnobjectYChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SightsDBModel", "FK_Events_CulturalAndHistoricSites", "Events")]
        public EntityCollection<Events> Events
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Events>("SightsDBModel.FK_Events_CulturalAndHistoricSites", "Events");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Events>("SightsDBModel.FK_Events_CulturalAndHistoricSites", "Events", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SightsDBModel", Name="Documents")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Documents : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Documents object.
        /// </summary>
        /// <param name="idDocument">Initial value of the idDocument property.</param>
        /// <param name="documentText">Initial value of the documentText property.</param>
        /// <param name="documentName">Initial value of the documentName property.</param>
        public static Documents CreateDocuments(global::System.Int32 idDocument, global::System.String documentText, global::System.String documentName)
        {
            Documents documents = new Documents();
            documents.idDocument = idDocument;
            documents.documentText = documentText;
            documents.documentName = documentName;
            return documents;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idDocument
        {
            get
            {
                return _idDocument;
            }
            set
            {
                if (_idDocument != value)
                {
                    OnidDocumentChanging(value);
                    ReportPropertyChanging("idDocument");
                    _idDocument = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idDocument");
                    OnidDocumentChanged();
                }
            }
        }
        private global::System.Int32 _idDocument;
        partial void OnidDocumentChanging(global::System.Int32 value);
        partial void OnidDocumentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String documentText
        {
            get
            {
                return _documentText;
            }
            set
            {
                OndocumentTextChanging(value);
                ReportPropertyChanging("documentText");
                _documentText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("documentText");
                OndocumentTextChanged();
            }
        }
        private global::System.String _documentText;
        partial void OndocumentTextChanging(global::System.String value);
        partial void OndocumentTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String documentName
        {
            get
            {
                return _documentName;
            }
            set
            {
                OndocumentNameChanging(value);
                ReportPropertyChanging("documentName");
                _documentName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("documentName");
                OndocumentNameChanged();
            }
        }
        private global::System.String _documentName;
        partial void OndocumentNameChanging(global::System.String value);
        partial void OndocumentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String area
        {
            get
            {
                return _area;
            }
            set
            {
                OnareaChanging(value);
                ReportPropertyChanging("area");
                _area = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("area");
                OnareaChanged();
            }
        }
        private global::System.String _area;
        partial void OnareaChanging(global::System.String value);
        partial void OnareaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String age
        {
            get
            {
                return _age;
            }
            set
            {
                OnageChanging(value);
                ReportPropertyChanging("age");
                _age = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("age");
                OnageChanged();
            }
        }
        private global::System.String _age;
        partial void OnageChanging(global::System.String value);
        partial void OnageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String importance
        {
            get
            {
                return _importance;
            }
            set
            {
                OnimportanceChanging(value);
                ReportPropertyChanging("importance");
                _importance = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("importance");
                OnimportanceChanged();
            }
        }
        private global::System.String _importance;
        partial void OnimportanceChanging(global::System.String value);
        partial void OnimportanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String culture
        {
            get
            {
                return _culture;
            }
            set
            {
                OncultureChanging(value);
                ReportPropertyChanging("culture");
                _culture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("culture");
                OncultureChanged();
            }
        }
        private global::System.String _culture;
        partial void OncultureChanging(global::System.String value);
        partial void OncultureChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SightsDBModel", Name="Events")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Events : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Events object.
        /// </summary>
        /// <param name="idEvent">Initial value of the idEvent property.</param>
        /// <param name="event">Initial value of the event property.</param>
        /// <param name="eventName">Initial value of the eventName property.</param>
        /// <param name="culturalAndHistoricSitesId">Initial value of the CulturalAndHistoricSitesId property.</param>
        public static Events CreateEvents(global::System.Int32 idEvent, global::System.String @event, global::System.String eventName, global::System.Int32 culturalAndHistoricSitesId)
        {
            Events events = new Events();
            events.idEvent = idEvent;
            events.@event = @event;
            events.eventName = eventName;
            events.CulturalAndHistoricSitesId = culturalAndHistoricSitesId;
            return events;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEvent
        {
            get
            {
                return _idEvent;
            }
            set
            {
                if (_idEvent != value)
                {
                    OnidEventChanging(value);
                    ReportPropertyChanging("idEvent");
                    _idEvent = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idEvent");
                    OnidEventChanged();
                }
            }
        }
        private global::System.Int32 _idEvent;
        partial void OnidEventChanging(global::System.Int32 value);
        partial void OnidEventChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String @event
        {
            get
            {
                return _event;
            }
            set
            {
                OneventChanging(value);
                ReportPropertyChanging("event");
                _event = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("event");
                OneventChanged();
            }
        }
        private global::System.String _event;
        partial void OneventChanging(global::System.String value);
        partial void OneventChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String eventName
        {
            get
            {
                return _eventName;
            }
            set
            {
                OneventNameChanging(value);
                ReportPropertyChanging("eventName");
                _eventName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("eventName");
                OneventNameChanged();
            }
        }
        private global::System.String _eventName;
        partial void OneventNameChanging(global::System.String value);
        partial void OneventNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String area
        {
            get
            {
                return _area;
            }
            set
            {
                OnareaChanging(value);
                ReportPropertyChanging("area");
                _area = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("area");
                OnareaChanged();
            }
        }
        private global::System.String _area;
        partial void OnareaChanging(global::System.String value);
        partial void OnareaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String age
        {
            get
            {
                return _age;
            }
            set
            {
                OnageChanging(value);
                ReportPropertyChanging("age");
                _age = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("age");
                OnageChanged();
            }
        }
        private global::System.String _age;
        partial void OnageChanging(global::System.String value);
        partial void OnageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.String _date;
        partial void OndateChanging(global::System.String value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CulturalAndHistoricSitesId
        {
            get
            {
                return _CulturalAndHistoricSitesId;
            }
            set
            {
                OnCulturalAndHistoricSitesIdChanging(value);
                ReportPropertyChanging("CulturalAndHistoricSitesId");
                _CulturalAndHistoricSitesId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CulturalAndHistoricSitesId");
                OnCulturalAndHistoricSitesIdChanged();
            }
        }
        private global::System.Int32 _CulturalAndHistoricSitesId;
        partial void OnCulturalAndHistoricSitesIdChanging(global::System.Int32 value);
        partial void OnCulturalAndHistoricSitesIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SightsDBModel", "FK_Events_CulturalAndHistoricSites", "CulturalAndHistoricSites")]
        public CulturalAndHistoricSites CulturalAndHistoricSites
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CulturalAndHistoricSites>("SightsDBModel.FK_Events_CulturalAndHistoricSites", "CulturalAndHistoricSites").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CulturalAndHistoricSites>("SightsDBModel.FK_Events_CulturalAndHistoricSites", "CulturalAndHistoricSites").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CulturalAndHistoricSites> CulturalAndHistoricSitesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CulturalAndHistoricSites>("SightsDBModel.FK_Events_CulturalAndHistoricSites", "CulturalAndHistoricSites");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CulturalAndHistoricSites>("SightsDBModel.FK_Events_CulturalAndHistoricSites", "CulturalAndHistoricSites", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SightsDBModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }

    #endregion
    
}
